-- Unit tests for project-tasks/detect.lua
local helpers = require("helpers")
local detect = require("project-tasks.detect")
local backends = require("project-tasks.backends")

describe("detect", function()
  describe("find_root", function()
    it("finds root with CMakePresets.json", function()
      local fixture = helpers.fixture_path("cmake-presets")
      local root = detect.find_root(fixture .. "/src")
      assert.equals(fixture, root)
    end)

    it("finds root with CMakeLists.txt", function()
      local fixture = helpers.fixture_path("cmake-no-presets")
      local root = detect.find_root(fixture .. "/src")
      assert.equals(fixture, root)
    end)

    it("finds root with pyproject.toml", function()
      local fixture = helpers.fixture_path("python-uv")
      local root = detect.find_root(fixture .. "/src")
      assert.equals(fixture, root)
    end)

    it("returns nil for non-project directory", function()
      local root = detect.find_root("/tmp")
      assert.is_nil(root)
    end)
  end)

  describe("get_backend", function()
    it("selects cmake backend for CMakePresets.json", function()
      local fixture = helpers.fixture_path("cmake-presets")
      local name, backend = detect.get_backend(fixture, backends)
      assert.equals("cmake", name)
      assert.is_not_nil(backend)
      assert.is_not_nil(backend.tasks.configure)
    end)

    it("selects cmake backend for CMakeLists.txt only", function()
      local fixture = helpers.fixture_path("cmake-no-presets")
      local name, backend = detect.get_backend(fixture, backends)
      assert.equals("cmake", name)
    end)

    it("selects python backend for pyproject.toml", function()
      local fixture = helpers.fixture_path("python-uv")
      local name, backend = detect.get_backend(fixture, backends)
      assert.equals("python", name)
      assert.is_not_nil(backend.tasks.run)
    end)

    it("returns nil for unknown project type", function()
      local name, backend = detect.get_backend("/tmp", backends)
      assert.is_nil(name)
      assert.is_nil(backend)
    end)
  end)

  describe("matches_markers", function()
    it("returns true when marker exists", function()
      local fixture = helpers.fixture_path("cmake-presets")
      local result = detect.matches_markers(fixture, { "CMakePresets.json" })
      assert.is_true(result)
    end)

    it("returns false when marker does not exist", function()
      local fixture = helpers.fixture_path("cmake-presets")
      local result = detect.matches_markers(fixture, { "Cargo.toml" })
      assert.is_false(result)
    end)

    it("returns true if any marker exists", function()
      local fixture = helpers.fixture_path("cmake-presets")
      local result = detect.matches_markers(fixture, { "Cargo.toml", "CMakeLists.txt" })
      assert.is_true(result)
    end)
  end)

  describe("has_marker", function()
    it("returns true for existing file", function()
      local fixture = helpers.fixture_path("cmake-presets")
      assert.is_true(detect.has_marker(fixture, "CMakePresets.json"))
    end)

    it("returns false for non-existing file", function()
      local fixture = helpers.fixture_path("cmake-presets")
      assert.is_false(detect.has_marker(fixture, "nonexistent.txt"))
    end)
  end)
end)
